@EventsManagement_HostAddress = http://localhost:5140

GET {{EventsManagement_HostAddress}}/api/institutions
Accept: application/json
Authorization:"Bearer  eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImJlZWU2ZWM3LTIwZTItMTFmMS1iNjJiLTE4NjAyNDQ5OTA5NyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImtpbnNseWJ5cm9uZTE3QGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE3NzM3MTcwMzgsImlzcyI6IkJ5cm9uZUtpbmdzbHlpZGY3MzkxODcyZTh5IiwiYXVkIjoiVG93aG9taXRtYXljb25jZXJuIn0.whVh0kwW8dDkvg14XUP_ZJkwovLYpPO5F3BlImar_-tvnLkbhxdTEHmJXp1pGb19yiSWyY0bqoeU_8981rCIKQ"

###
